export type ReelGroup = "KI im Alltag" | "KI bei der Arbeit" | "Marketing" | "Verkauf";

export type ReelScript = {
  num: number;
  group: ReelGroup;
  title: string;
  hookDe: string; hookRu: string;
  midDe: string; midRu: string;
  cta: "A" | "B" | "C" | "D" | "E";
  saveWhy: string;
  captionDe: string;
  captionRu: string;
  hashtags: [string, string, string, string, string];
  shoot: string;
};

export const REEL_GROUPS: {
  id: ReelGroup;
  emoji: string;
  badge: "accent" | "blue" | "amber" | "pink" | "purple";
  count: number;
  note: string;
}[] = [
  { id: "KI im Alltag",      emoji: "🧠", badge: "accent", count: 8, note: "Широкая аудитория, двигатель роста: приёмы для жизни, которые работают сегодня же" },
  { id: "KI bei der Arbeit", emoji: "⚡", badge: "blue",   count: 7, note: "Рутина малого бизнеса: документы, письма, счета, клиенты — экономия часов в неделю" },
  { id: "Marketing",         emoji: "📣", badge: "amber",  count: 8, note: "Чтобы находили: Google, отзывы, видимость в ИИ, контент и скорость ответа" },
  { id: "Verkauf",           emoji: "💰", badge: "pink",   count: 7, note: "Деньги: цена без страха, дожим, возражения, повышение цен, плохие клиенты" },
];

export const SCRIPTS: ReelScript[] = [
  // ─────────────────────────────  KI im Alltag  ─────────────────────────────
  {
    num: 101, group: "KI im Alltag", title: "Wo ist mein Geld hin? (Kassenzettel-Trick)",
    hookDe: "Am Monatsende ist das Konto leer und du weißt nicht, wofür. In 10 Minuten weißt du es.",
    hookRu: "В конце месяца счёт пустой, и ты не знаешь, на что ушло. Через 10 минут будешь знать.",
    midDe: "Sammle einen Monat lang jeden Kassenzettel in einem Foto-Album am Handy. Dann alle Fotos in die KI und schreib: «Lies alle Belege. Mach eine Tabelle: Datum, Geschäft, Betrag, Kategorie. Am Ende die Summe pro Kategorie, sortiert nach Höhe.» Du siehst sofort die zwei Kategorien, die dich auffressen. Meistens sind es nicht die großen Sachen.",
    midRu: "Месяц складывай все чеки в один фотоальбом на телефоне. Потом все фото в ИИ и напиши: «Прочитай все чеки. Сделай таблицу: дата, магазин, сумма, категория. В конце — сумма по каждой категории, по убыванию». Сразу видишь две категории, которые тебя съедают. Обычно это не крупные покупки.",
    cta: "C",
    saveWhy: "Готовый промпт + система, которую надо начать сегодня — сохраняют, чтобы вернуться в конце месяца.",
    captionDe: "Nicht sparen. Erst sehen.\n\nSo geht's: einen Monat lang jeden Kassenzettel fotografieren, alle in ein Album. Dann alle Fotos in die KI:\n\n„Lies alle Belege. Mach eine Tabelle: Datum, Geschäft, Betrag, Kategorie. Am Ende die Summe pro Kategorie, sortiert nach Höhe.“\n\nDie zwei größten Kategorien überraschen fast jeden.\n\nSchreib „KI“ in die Kommentare — ich schicke dir den Prompt als Text.\nSpeichern, sonst suchst du ihn am Monatsende.",
    captionRu: "Не экономить. Сначала увидеть.\n\nКак делать: месяц фотографируй каждый чек, все в один альбом. Потом все фото в ИИ:\n\n«Прочитай все чеки. Сделай таблицу: дата, магазин, сумма, категория. В конце — сумма по категориям, по убыванию».\n\nДве самые большие категории удивляют почти каждого.\n\nНапиши «KI» в комментарии — пришлю промпт текстом.\nСохрани, иначе будешь искать в конце месяца.",
    hashtags: ["#kimitandrii", "#haushaltsbudget", "#geldsparen", "#chatgpttipps", "#kiimalltag"],
    shoot: "Экран телефона: альбом с чеками → готовая таблица с суммами. Реквизит — горсть настоящих чеков в руке в первые 2 секунды.",
  },
  {
    num: 102, group: "KI im Alltag", title: "Kühlschrank-Foto → Essensplan",
    hookDe: "Ein Foto vom Kühlschrank spart dir diese Woche zwei Einkäufe.",
    hookRu: "Одно фото холодильника экономит тебе на этой неделе две поездки в магазин.",
    midDe: "Kühlschrank auf, Foto machen, in die KI laden. Prompt: «Das ist mein Kühlschrank. Plane vier Abendessen, die ich damit kochen kann. Nenne nur die Zutaten, die wirklich fehlen — als eine kurze Einkaufsliste.» Du kochst weg, was da ist, und kaufst nur die Lücken. Weniger weggeworfenes Essen, weniger Zwischeneinkäufe, kein Abend mehr mit der Frage «Was koche ich heute?».",
    midRu: "Открыл холодильник, сфотографировал, загрузил в ИИ. Промпт: «Это мой холодильник. Составь четыре ужина из того, что есть. Перечисли только те продукты, которых реально не хватает — коротким списком покупок». Ты доедаешь то, что есть, и докупаешь только дырки. Меньше выброшенной еды, меньше забегов в магазин, и больше нет вечернего вопроса «что готовить?».",
    cta: "A",
    saveWhy: "Пересылают партнёру/жене в тот же вечер — бытовая боль каждой семьи.",
    captionDe: "Kühlschrank auf. Foto. Fertig.\n\n„Das ist mein Kühlschrank. Plane vier Abendessen, die ich damit kochen kann. Nenne nur die Zutaten, die wirklich fehlen — als kurze Einkaufsliste.“\n\nDu kochst weg, was da ist. Du kaufst nur die Lücken.\nWeniger Müll, weniger Einkäufe, kein „Was koche ich heute?“ mehr.\n\nSchick das jemandem, der jeden Abend vor dem offenen Kühlschrank steht.",
    captionRu: "Открыл холодильник. Фото. Готово.\n\n«Это мой холодильник. Составь четыре ужина из того, что есть. Перечисли только те продукты, которых не хватает — коротким списком покупок».\n\nТы доедаешь то, что есть. Докупаешь только дырки.\nМеньше мусора, меньше походов в магазин, больше нет «что сегодня готовить?».\n\nОтправь это тому, кто каждый вечер стоит перед открытым холодильником.",
    hashtags: ["#kimitandrii", "#mealprep", "#essensplan", "#kiimalltag", "#lebensmittelrettung"],
    shoot: "Снять дома: открываешь холодильник, щёлк — и сразу экран с планом на 4 ужина. Быстрый монтаж, 25 секунд.",
  },
  {
    num: 103, group: "KI im Alltag", title: "Die Reklamation, die dein Geld zurückholt",
    hookDe: "Die meisten reklamieren nicht, weil sie nicht wissen, wie man das auf Deutsch schreibt. Das kostet dich Geld.",
    hookRu: "Большинство не жалуется, потому что не знает, как это написать по-немецки. Это стоит тебе денег.",
    midDe: "Foto vom Produkt und von der Rechnung in die KI. Prompt: «Schreib eine Reklamation an diesen Händler. Sachlich, höflich, keine Drohung. Nenne das Problem, das Kaufdatum und was ich will: Reparatur, Austausch oder Geld zurück. Setz eine Frist von 14 Tagen.» Wichtig: Kontonummer und persönliche Daten vorher wegschneiden. Höflich und konkret wirkt in Österreich besser als wütend.",
    midRu: "Фото товара и счёта в ИИ. Промпт: «Напиши рекламацию этому продавцу. По делу, вежливо, без угроз. Назови проблему, дату покупки и чего я хочу: ремонт, замену или возврат денег. Поставь срок 14 дней». Важно: номер счёта и личные данные заранее замазать. Вежливо и конкретно в Австрии работает лучше, чем зло.",
    cta: "C",
    saveWhy: "Прямая выгода в евро + снимает языковой барьер — сохраняют «на случай».",
    captionDe: "Kaputt gekauft und nichts gesagt? Das ist geschenktes Geld.\n\nFoto vom Produkt + Rechnung in die KI:\n\n„Schreib eine Reklamation an diesen Händler. Sachlich, höflich, keine Drohung. Nenne Problem, Kaufdatum und was ich will: Reparatur, Austausch oder Geld zurück. Frist: 14 Tage.“\n\nPersönliche Daten vorher wegschneiden.\nHöflich und konkret schlägt wütend — jedes Mal.\n\nSchreib „KI“ in die Kommentare, ich schicke dir die Vorlage.",
    captionRu: "Купил бракованное и промолчал? Это подаренные деньги.\n\nФото товара + счёт в ИИ:\n\n«Напиши рекламацию этому продавцу. По делу, вежливо, без угроз. Назови проблему, дату покупки и чего я хочу: ремонт, замену или возврат денег. Срок: 14 дней».\n\nЛичные данные заранее убрать.\nВежливо и конкретно бьёт злость — всегда.\n\nНапиши «KI» в комментарии — пришлю шаблон.",
    hashtags: ["#kimitandrii", "#reklamation", "#verbraucherschutz", "#kitipps", "#österreich"],
    shoot: "Реквизит: сломанная вещь на столе. Экран: письмо появляется за 5 секунд. Тон спокойный, не агрессивный.",
  },
  {
    num: 104, group: "KI im Alltag", title: "Was zahlst du da eigentlich jeden Monat?",
    hookDe: "Du zahlst jeden Monat für etwas, das du vor drei Jahren unterschrieben hast. Weißt du noch, was drinsteht?",
    hookRu: "Ты платишь каждый месяц за то, что подписал три года назад. Помнишь, что там написано?",
    midDe: "Nimm einen Vertrag: Handy, Versicherung, Fitness, Streaming. Foto oder PDF in die KI, Daten vorher abdecken. Prompt: «Fasse diesen Vertrag in fünf Punkten zusammen: was zahle ich, was bekomme ich, wie lange läuft er, bis wann kann ich kündigen, was ist ungewöhnlich?» Dann die zweite Frage: «Welche drei Fragen soll ich dem Anbieter stellen?» Kein Ersatz für Beratung — aber du gehst informiert ins Gespräch.",
    midRu: "Возьми один договор: мобильный, страховка, фитнес, подписка. Фото или PDF в ИИ, личные данные закрыть. Промпт: «Суммируй этот договор в пяти пунктах: что я плачу, что получаю, сколько он идёт, до когда можно расторгнуть, что необычного?» Потом второй вопрос: «Какие три вопроса задать провайдеру?» Это не замена консультации — но в разговор ты идёшь подготовленным.",
    cta: "C",
    saveWhy: "Один вечер = отменённые подписки, которые платились годами.",
    captionDe: "Ein Abend, ein Ordner, alle Verträge.\n\n„Fasse diesen Vertrag in fünf Punkten zusammen: was zahle ich, was bekomme ich, wie lange läuft er, bis wann kann ich kündigen, was ist ungewöhnlich?“\n\nDann: „Welche drei Fragen soll ich dem Anbieter stellen?“\n\nPersönliche Daten vorher abdecken. Und bei großen Verträgen: fachlich prüfen lassen.\n\nSchreib „KI“ in die Kommentare — ich schicke dir beide Prompts.",
    captionRu: "Один вечер, одна папка, все договоры.\n\n«Суммируй этот договор в пяти пунктах: что я плачу, что получаю, сколько он идёт, до когда можно расторгнуть, что необычного?»\n\nПотом: «Какие три вопроса задать провайдеру?»\n\nЛичные данные заранее закрыть. По крупным договорам — проверить у специалиста.\n\nНапиши «KI» в комментарии — пришлю оба промпта.",
    hashtags: ["#kimitandrii", "#verträge", "#fixkosten", "#kündigen", "#kiimalltag"],
    shoot: "Стопка бумаг на столе, листаешь. Экран: пять пунктов появляются списком. Финальный кадр — вычеркнутая подписка.",
  },
  {
    num: 105, group: "KI im Alltag", title: "Hausaufgaben: der Prompt, der nicht die Lösung verrät",
    hookDe: "Wenn dein Kind die KI nach Hausaufgaben fragt, bekommt es die Antwort. Und lernt nichts. Ein Satz ändert das.",
    hookRu: "Если ребёнок спрашивает ИИ про домашку, он получает ответ. И ничему не учится. Одна фраза это меняет.",
    midDe: "Der Satz lautet: «Gib mir nicht die Lösung.» Kompletter Prompt: «Mein Kind ist neun und versteht dieses Thema nicht. Erkläre es in drei einfachen Sätzen mit einem Beispiel aus dem Alltag. Dann stell drei Fragen, um zu prüfen, ob es verstanden wurde. Gib die Lösung der Aufgabe nicht.» Aus dem Antwort-Automaten wird ein geduldiger Nachhilfelehrer, der nie müde wird. Funktioniert bei Erwachsenen genauso.",
    midRu: "Фраза такая: «Не давай мне решение». Полный промпт: «Моему ребёнку девять, он не понимает эту тему. Объясни в трёх простых предложениях с примером из жизни. Потом задай три вопроса, чтобы проверить понимание. Решение задачи не давай». Автомат ответов превращается в терпеливого репетитора, который не устаёт. Со взрослыми работает так же.",
    cta: "A",
    saveWhy: "Родители пересылают в школьные чаты — тема вины «ребёнок списывает у ИИ».",
    captionDe: "Die KI macht die Hausaufgaben? Falscher Prompt.\n\n„Mein Kind ist neun und versteht dieses Thema nicht. Erkläre es in drei einfachen Sätzen mit einem Beispiel aus dem Alltag. Dann stell drei Fragen, um zu prüfen, ob es verstanden wurde. Gib die Lösung nicht.“\n\nEin Satz macht aus dem Antwort-Automaten einen geduldigen Nachhilfelehrer.\n\nFür Erwachsene funktioniert genau derselbe Prompt.\nSchick ihn den Eltern, die abends am Küchentisch verzweifeln.",
    captionRu: "ИИ делает домашку за ребёнка? Неправильный промпт.\n\n«Моему ребёнку девять, он не понимает эту тему. Объясни в трёх простых предложениях с примером из жизни. Потом задай три вопроса, чтобы проверить понимание. Решение не давай».\n\nОдна фраза превращает автомат ответов в терпеливого репетитора.\n\nДля взрослых работает ровно тот же промпт.\nОтправь родителям, которые вечером мучаются за кухонным столом.",
    hashtags: ["#kimitandrii", "#hausaufgaben", "#lernenmitki", "#elterntipps", "#chatgpttipps"],
    shoot: "Кухонный стол, тетрадь, телефон. Показать два экрана рядом: слева готовый ответ, справа объяснение с вопросами.",
  },
  {
    num: 106, group: "KI im Alltag", title: "Vor dem Arzttermin: die Fragenliste",
    hookDe: "Du gehst zum Arzt, und draußen fallen dir die drei wichtigen Fragen ein. Jedes Mal.",
    hookRu: "Выходишь от врача — и на улице вспоминаешь три важных вопроса. Каждый раз.",
    midDe: "Am Abend davor in die KI: «Ich habe morgen einen Termin wegen [Thema]. Schreib mir zehn Fragen, die ich stellen sollte — nach Wichtigkeit sortiert. Kurz und in einfachen Worten.» Liste aufs Handy, im Termin abhaken. Nach dem Termin: Befund fotografieren und «Erkläre das in einfachen Worten» — nur zum Verstehen. Die KI stellt keine Diagnose und ersetzt keinen Arzt. Sie sorgt dafür, dass du im Zimmer nichts vergisst.",
    midRu: "Вечером накануне в ИИ: «Завтра у меня приём по поводу [тема]. Напиши десять вопросов, которые стоит задать — по важности. Коротко и простыми словами». Список в телефон, на приёме отмечаешь. После приёма: сфоткать заключение и «объясни простыми словами» — только чтобы понять. ИИ не ставит диагноз и не заменяет врача. Он делает так, чтобы ты ничего не забыл в кабинете.",
    cta: "A",
    saveWhy: "Сохраняют перед конкретным приёмом; тема близка всем, особенно с неродным немецким.",
    captionDe: "Im Sprechzimmer vergisst man alles. Deshalb: Liste.\n\nAm Abend davor:\n„Ich habe morgen einen Termin wegen [Thema]. Schreib mir zehn Fragen, die ich stellen sollte — nach Wichtigkeit sortiert, kurz und in einfachen Worten.“\n\nDanach den Befund fotografieren: „Erkläre das in einfachen Worten.“ Nur zum Verstehen.\n\nDie KI stellt keine Diagnose und ersetzt keinen Arzt. Sie sorgt dafür, dass du vorbereitet reingehst.",
    captionRu: "В кабинете всё вылетает из головы. Поэтому — список.\n\nВечером накануне:\n«Завтра приём по поводу [тема]. Напиши десять вопросов, которые стоит задать — по важности, коротко и простыми словами».\n\nПосле — сфотографировать заключение: «объясни простыми словами». Только чтобы понять.\n\nИИ не ставит диагноз и не заменяет врача. Он нужен, чтобы ты зашёл подготовленным.",
    hashtags: ["#kimitandrii", "#arzttermin", "#gesundheitskompetenz", "#kiimalltag", "#wien"],
    shoot: "Снять у входа в клинику или дома вечером. Крупно: список вопросов в заметках телефона, галочки.",
  },
  {
    num: 107, group: "KI im Alltag", title: "Behördenanruf auf Deutsch — der Spickzettel",
    hookDe: "Ich habe einen Anruf drei Tage vor mir hergeschoben. Nicht wegen der Sache. Wegen der Sprache.",
    hookRu: "Я три дня откладывал один звонок. Не из-за дела. Из-за языка.",
    midDe: "Seitdem mache ich das so. Prompt: «Ich rufe [Stelle] an wegen [Thema]. Mein Deutsch ist B1. Schreib mir: den ersten Satz, zehn einfache Sätze, die ich brauchen werde, fünf Fragen, die man mir stellen wird, und was ich sage, wenn ich etwas nicht verstehe.» Der letzte Teil ist der wichtigste: «Können Sie das bitte langsamer wiederholen?» Zettel neben das Telefon. Der Anruf dauert dann vier Minuten.",
    midRu: "С тех пор делаю так. Промпт: «Я звоню в [инстанцию] по поводу [тема]. Мой немецкий B1. Напиши: первую фразу, десять простых фраз, которые понадобятся, пять вопросов, которые мне зададут, и что сказать, если я не понял». Последняя часть — самая важная: «Können Sie das bitte langsamer wiederholen?» Листок рядом с телефоном. Звонок занимает четыре минуты.",
    cta: "A",
    saveWhy: "Личное признание + рабочая шпаргалка: пересылают все, кто живёт с неродным немецким.",
    captionDe: "Nicht die Sache macht Angst. Die Sprache macht Angst.\n\n„Ich rufe [Stelle] an wegen [Thema]. Mein Deutsch ist B1. Schreib mir: den ersten Satz, zehn einfache Sätze, die ich brauchen werde, fünf Fragen, die man mir stellen wird, und was ich sage, wenn ich etwas nicht verstehe.“\n\nDer wichtigste Satz auf dem Zettel:\n„Können Sie das bitte langsamer wiederholen?“\n\nZettel neben das Telefon. Vier Minuten, erledigt.\nSpeichern für den Anruf, den du gerade aufschiebst.",
    captionRu: "Страшно не дело. Страшно язык.\n\n«Я звоню в [инстанцию] по поводу [тема]. Мой немецкий B1. Напиши: первую фразу, десять простых фраз, которые понадобятся, пять вопросов, которые мне зададут, и что сказать, если я не понял».\n\nСамая важная фраза на листке:\n«Können Sie das bitte langsamer wiederholen?»\n\nЛисток рядом с телефоном. Четыре минуты — и готово.\nСохрани для звонка, который ты сейчас откладываешь.",
    hashtags: ["#kimitandrii", "#deutschlernen", "#lebeninwien", "#behörden", "#sprachbarriere"],
    shoot: "Честно, в камеру, дома. Показать реальный листок с фразами и телефон. Личная интонация — это ролик про себя.",
  },
  {
    num: 108, group: "KI im Alltag", title: "Urlaub planen: drei Prompts statt zwanzig Tabs",
    hookDe: "Zwanzig offene Tabs, drei Stunden weg, immer noch nichts gebucht. Kennst du?",
    hookRu: "Двадцать открытых вкладок, три часа прошло, ничего не забронировано. Знакомо?",
    midDe: "Drei Prompts, in dieser Reihenfolge. Erstens: «Wir sind [wer], [wie viele Tage] in [Ort], Budget [Summe]. Mach drei Tagespläne — entspannt, aktiv, mit Kindern.» Zweitens: «Was davon muss man vorher buchen und was kann man spontan machen?» Drittens, der Prompt, den alle vergessen: «Was machen wir dort, wenn es regnet?» Am Ende: «Fasse alles als Checkliste zusammen.» Die Liste ins Handy, fertig.",
    midRu: "Три промпта, именно в таком порядке. Первый: «Нас [кто], [сколько дней] в [месте], бюджет [сумма]. Сделай три плана на день — спокойный, активный, с детьми». Второй: «Что нужно бронировать заранее, а что можно спонтанно?» Третий, про который все забывают: «Что делать там, если дождь?» В конце: «Собери всё в чек-лист». Список в телефон — готово.",
    cta: "A",
    saveWhy: "Сезонный и практичный: сохраняют до отпуска, пересылают тому, с кем едут.",
    captionDe: "Drei Prompts statt drei Stunden Tabs.\n\n1. „Wir sind [wer], [Tage] in [Ort], Budget [Summe]. Mach drei Tagespläne: entspannt, aktiv, mit Kindern.“\n2. „Was muss man vorher buchen, was geht spontan?“\n3. „Was machen wir dort, wenn es regnet?“\n\nDann: „Fasse alles als Checkliste zusammen.“\n\nPunkt 3 rettet dir mindestens einen Urlaubstag.\nSpeichern für die nächste Reise.",
    captionRu: "Три промпта вместо трёх часов вкладок.\n\n1. «Нас [кто], [дней] в [месте], бюджет [сумма]. Сделай три плана на день: спокойный, активный, с детьми».\n2. «Что бронировать заранее, что можно спонтанно?»\n3. «Что делать там, если дождь?»\n\nПотом: «Собери всё в чек-лист».\n\nПункт 3 спасает минимум один день отпуска.\nСохрани до следующей поездки.",
    hashtags: ["#kimitandrii", "#urlaubsplanung", "#reisetipps", "#chatgpttipps", "#kiimalltag"],
    shoot: "Ноутбук с кучей вкладок → закрываешь все → телефон с готовым чек-листом. Динамично, 20 секунд.",
  },

  // ─────────────────────────  KI bei der Arbeit  ─────────────────────────
  {
    num: 109, group: "KI bei der Arbeit", title: "40 Sekunden sprechen → fertiges Angebot",
    hookDe: "Der Handwerker war um vier fertig. Das Angebot schreibt er um halb elf am Abend. Muss nicht sein.",
    hookRu: "Мастер закончил в четыре. Смету пишет в половине одиннадцатого вечера. Так не должно быть.",
    midDe: "Direkt im Auto nach dem Termin: Sprachnachricht an dich selbst, 40 Sekunden, ganz normal reden. Was der Kunde will, was du machst, wie lange, was es kostet. Dann in die KI: «Das ist meine Sprachnotiz von einem Kundentermin. Mach daraus ein Angebot: kurze Einleitung, Leistungen als Liste, Preis, Zeitraum, Gültigkeit 14 Tage. Sachlich, höflich, ohne Werbesprache.» Du liest drüber, korrigierst den Preis, schickst raus. Vor Ort statt am Abend.",
    midRu: "Прямо в машине после встречи: голосовое самому себе, 40 секунд, обычной речью. Что клиент хочет, что делаешь, сколько по времени, сколько стоит. Потом в ИИ: «Это моя голосовая заметка со встречи с клиентом. Сделай из неё смету: короткое вступление, работы списком, цена, сроки, действует 14 дней. По делу, вежливо, без рекламных слов». Ты перечитываешь, правишь цену, отправляешь. На месте, а не вечером.",
    cta: "C",
    saveWhy: "Ремесленники узнают себя в вечерней бумажной работе — сохраняют и пересылают коллегам.",
    captionDe: "Angebote am Abend schreiben? Das war einmal.\n\nIm Auto nach dem Termin: 40 Sekunden Sprachnachricht an dich selbst. Ganz normal reden.\n\nDann in die KI:\n„Das ist meine Sprachnotiz von einem Kundentermin. Mach daraus ein Angebot: kurze Einleitung, Leistungen als Liste, Preis, Zeitraum, Gültigkeit 14 Tage. Sachlich, ohne Werbesprache.“\n\nDrüberlesen, Preis prüfen, senden. Noch vor der nächsten Baustelle.\n\nSchreib „KI“ in die Kommentare — ich schicke dir den Prompt.",
    captionRu: "Писать сметы по вечерам? Это в прошлом.\n\nВ машине после встречи: 40 секунд голосового самому себе. Обычной речью.\n\nПотом в ИИ:\n«Это моя голосовая заметка со встречи. Сделай смету: короткое вступление, работы списком, цена, сроки, действует 14 дней. По делу, без рекламных слов».\n\nПеречитал, проверил цену, отправил. Ещё до следующего объекта.\n\nНапиши «KI» в комментарии — пришлю промпт.",
    hashtags: ["#kimitandrii", "#handwerk", "#angebot", "#selbstständig", "#kifürunternehmen"],
    shoot: "Снять в машине: диктуешь голосовое → экран с готовой сметой. Реквизит — рабочая одежда, планшет.",
  },
  {
    num: 110, group: "KI bei der Arbeit", title: "Fünf Antworten, die du nie wieder tippst",
    hookDe: "Du beantwortest jeden Tag dieselben fünf Fragen. Von Hand. Seit Jahren.",
    hookRu: "Ты каждый день отвечаешь на одни и те же пять вопросов. Руками. Годами.",
    midDe: "Heute Abend, einmal, 20 Minuten. Schreib deine fünf häufigsten Kundenfragen auf und gib sie der KI: «Das sind meine fünf häufigsten Kundenfragen. Schreib zu jeder eine Antwort: maximal drei Sätze, freundlich, mit einer Rückfrage am Ende, damit das Gespräch weitergeht.» Die fünf Antworten kommen in WhatsApp Business unter «Schnellantworten». Ab morgen: zwei Sekunden statt fünf Minuten — und die Rückfrage am Ende bringt dir die Termine.",
    midRu: "Сегодня вечером, один раз, 20 минут. Выпиши пять самых частых вопросов клиентов и отдай ИИ: «Вот мои пять самых частых вопросов от клиентов. Напиши на каждый ответ: максимум три предложения, дружелюбно, с встречным вопросом в конце, чтобы разговор продолжился». Пять ответов сохраняешь в WhatsApp Business в «быстрые ответы». С завтрашнего дня: две секунды вместо пяти минут — а встречный вопрос приносит записи.",
    cta: "C",
    saveWhy: "Разовая настройка с ежедневной отдачей — классический «сохранить и сделать в воскресенье».",
    captionDe: "Fünf Fragen. Jeden Tag. Von Hand. Seit Jahren.\n\nEinmal 20 Minuten investieren:\n\n„Das sind meine fünf häufigsten Kundenfragen. Schreib zu jeder eine Antwort: maximal drei Sätze, freundlich, mit einer Rückfrage am Ende.“\n\nDie Antworten kommen in WhatsApp Business unter „Schnellantworten“.\n\nDie Rückfrage am Ende ist der Trick — sie macht aus einer Auskunft einen Termin.\n\nSchreib „KI“ in die Kommentare, ich schicke dir die Anleitung.",
    captionRu: "Пять вопросов. Каждый день. Руками. Годами.\n\nВложи один раз 20 минут:\n\n«Вот мои пять самых частых вопросов клиентов. Напиши на каждый ответ: максимум три предложения, дружелюбно, с встречным вопросом в конце».\n\nОтветы сохраняешь в WhatsApp Business в «быстрые ответы».\n\nВстречный вопрос в конце — это и есть трюк: справка превращается в запись.\n\nНапиши «KI» в комментарии — пришлю инструкцию.",
    hashtags: ["#kimitandrii", "#whatsappbusiness", "#kundenservice", "#kleinunternehmen", "#zeitsparen"],
    shoot: "Экран телефона: настройка быстрых ответов в WhatsApp Business, потом ответ клиенту в один тап.",
  },
  {
    num: 111, group: "KI bei der Arbeit", title: "Er zahlt nicht: die drei Nachrichten",
    hookDe: "Die Rechnung ist offen, du schreibst nicht. Weil du nicht unangenehm sein willst. Er merkt das.",
    hookRu: "Счёт не оплачен, а ты не пишешь. Потому что не хочешь быть неприятным. Он это чувствует.",
    midDe: "Bau dir die drei Nachrichten einmal fertig hin. Prompt: «Schreib drei Zahlungserinnerungen für eine offene Rechnung. Erste: freundlich, Tag 7, vielleicht übersehen. Zweite: bestimmt, Tag 14, mit klarer Frist. Dritte: sachlich, Tag 21, letzte Frist vor weiteren Schritten. Höflich, kurz, keine Drohungen.» Speichern, Datum, Name, Betrag eintragen, senden. Nicht du bist unangenehm — der Ablauf macht das für dich.",
    midRu: "Собери три сообщения один раз. Промпт: «Напиши три напоминания об оплате по неоплаченному счёту. Первое: дружелюбно, день 7, возможно просто не заметили. Второе: твёрдо, день 14, с чётким сроком. Третье: по делу, день 21, последний срок перед дальнейшими шагами. Вежливо, коротко, без угроз». Сохранил, подставил дату, имя, сумму, отправил. Неприятный не ты — за тебя это делает процедура.",
    cta: "C",
    saveWhy: "Больная тема самозанятых; шаблон нужен ровно в момент неоплаты — сохраняют заранее.",
    captionDe: "Nicht nachfragen ist teuer.\n\nEinmal bauen, immer benutzen:\n\n„Schreib drei Zahlungserinnerungen für eine offene Rechnung. Erste: freundlich, Tag 7. Zweite: bestimmt, Tag 14, mit klarer Frist. Dritte: sachlich, Tag 21, letzte Frist vor weiteren Schritten. Höflich, kurz, keine Drohungen.“\n\nDann nur noch Name, Betrag, Datum einsetzen.\n\nNicht du bist unangenehm. Der Ablauf ist es.\nSchreib „KI“ in die Kommentare — ich schicke dir alle drei Texte.",
    captionRu: "Не напоминать — дорого.\n\nСобрать один раз, пользоваться всегда:\n\n«Напиши три напоминания об оплате. Первое: дружелюбно, день 7. Второе: твёрдо, день 14, с чётким сроком. Третье: по делу, день 21, последний срок перед дальнейшими шагами. Вежливо, коротко, без угроз».\n\nДальше только подставляешь имя, сумму, дату.\n\nНеприятный не ты. Неприятная — процедура.\nНапиши «KI» в комментарии — пришлю все три текста.",
    hashtags: ["#kimitandrii", "#rechnung", "#selbstständigkeit", "#zahlungsmoral", "#kleinunternehmen"],
    shoot: "Разыграть за двоих: смотришь на неоплаченный счёт → три сообщения на экране с подписями Tag 7 / 14 / 21.",
  },
  {
    num: 112, group: "KI bei der Arbeit", title: "Nach dem Gespräch: wer hat was versprochen?",
    hookDe: "Zwei Wochen später sagt der Kunde: «Das war doch inklusive.» Und du weißt es nicht mehr genau.",
    hookRu: "Через две недели клиент говорит: «Это же входило в стоимость». А ты уже точно не помнишь.",
    midDe: "Nach jedem Kundengespräch: zwei Minuten Sprachnotiz, was besprochen wurde. Dann in die KI: «Aus dieser Notiz: Was habe ich versprochen? Was hat der Kunde versprochen? Welche Termine und Fristen? Was ist noch offen? Als kurze Liste.» Das Ergebnis schickst du dem Kunden per Mail: «Kurz zusammengefasst, damit wir dasselbe verstanden haben.» Zwei Minuten Arbeit. Damit sind Diskussionen später vorbei — und du wirkst professioneller als die meisten.",
    midRu: "После каждой встречи с клиентом: две минуты голосовой заметки, о чём договорились. Потом в ИИ: «Из этой заметки: что пообещал я? Что пообещал клиент? Какие даты и сроки? Что осталось открытым? Коротким списком». Результат отправляешь клиенту письмом: «Коротко подытожил, чтобы мы поняли одинаково». Две минуты работы. Споров потом нет — и выглядишь профессиональнее большинства.",
    cta: "A",
    saveWhy: "Защищает от конфликтов и переделок — «почему я так не делал» реакция у владельцев.",
    captionDe: "„Das war doch inklusive.“ — Diskussion, die du gewinnen kannst.\n\nNach jedem Termin: zwei Minuten Sprachnotiz. Dann:\n\n„Aus dieser Notiz: Was habe ich versprochen? Was hat der Kunde versprochen? Welche Termine und Fristen? Was ist offen? Als kurze Liste.“\n\nDas Ergebnis per Mail an den Kunden:\n„Kurz zusammengefasst, damit wir dasselbe verstanden haben.“\n\nZwei Minuten. Und keine Diskussion in vier Wochen.",
    captionRu: "«Это же входило» — спор, который можно выиграть.\n\nПосле каждой встречи: две минуты голосовой заметки. Потом:\n\n«Из этой заметки: что пообещал я? Что пообещал клиент? Какие даты и сроки? Что осталось открытым? Коротким списком».\n\nРезультат письмом клиенту:\n«Коротко подытожил, чтобы мы поняли одинаково».\n\nДве минуты. И никаких споров через месяц.\n\nСохрани — пригодится после ближайшей встречи.",
    hashtags: ["#kimitandrii", "#kundenkommunikation", "#projektmanagement", "#selbstständig", "#kifürunternehmen"],
    shoot: "Выход со встречи, диктуешь в телефон на ходу → экран с готовым списком договорённостей.",
  },
  {
    num: 113, group: "KI bei der Arbeit", title: "Das Postfach, das sich selbst sortiert",
    hookDe: "217 ungelesene Mails. Und die eine wichtige liegt irgendwo dazwischen.",
    hookRu: "217 непрочитанных писем. И одно важное лежит где-то между ними.",
    midDe: "Eine Stunde, einmal. Erstens: drei Filter anlegen — Newsletter, Rechnungen, Kundenanfragen. Alles, was kein Mensch geschrieben hat, überspringt den Posteingang. Zweitens: die KI fragen «Schreib mir vier Standard-Antworten: Anfrage bestätigen, Termin vorschlagen, Angebot nachfassen, höflich absagen. Je maximal fünf Zeilen.» Die vier als Vorlagen speichern. Drittens: Posteingang zweimal am Tag, nicht ständig. Das Postfach ist danach eine To-do-Liste, kein Briefkasten.",
    midRu: "Один час, один раз. Первое: создать три фильтра — рассылки, счета, запросы клиентов. Всё, что писал не человек, минует входящие. Второе: спросить ИИ «Напиши четыре стандартных ответа: подтвердить запрос, предложить встречу, дожать смету, вежливо отказать. Каждый максимум пять строк». Сохранить как шаблоны. Третье: заходить в почту два раза в день, а не постоянно. После этого почта — список задач, а не почтовый ящик.",
    cta: "A",
    saveWhy: "Конкретная система за час с понятным результатом — сохраняют «сделать в выходные».",
    captionDe: "217 ungelesene Mails sind kein Fleiß-Problem. Es ist ein System-Problem.\n\nEine Stunde, einmal:\n1. Drei Filter: Newsletter, Rechnungen, Kundenanfragen. Was kein Mensch geschrieben hat, überspringt den Posteingang.\n2. Vier Vorlagen von der KI: „Schreib vier Standard-Antworten: Anfrage bestätigen, Termin vorschlagen, Angebot nachfassen, höflich absagen. Je maximal fünf Zeilen.“\n3. Postfach zweimal am Tag statt ständig.\n\nDanach ist dein Postfach eine To-do-Liste. Kein Briefkasten.",
    captionRu: "217 непрочитанных — это не про лень. Это про отсутствие системы.\n\nОдин час, один раз:\n1. Три фильтра: рассылки, счета, запросы клиентов. Что писал не человек — мимо входящих.\n2. Четыре шаблона от ИИ: «Напиши четыре стандартных ответа: подтвердить запрос, предложить встречу, дожать смету, вежливо отказать. Каждый максимум пять строк».\n3. Почта два раза в день, а не постоянно.\n\nПосле этого почта — список задач. Не ящик.",
    hashtags: ["#kimitandrii", "#produktivität", "#emailmanagement", "#zeitmanagement", "#selbstständig"],
    shoot: "Экран: 217 непрочитанных → настройка фильтров ускоренно → чистые входящие с 4 письмами.",
  },
  {
    num: 114, group: "KI bei der Arbeit", title: "Rechnung raus? Erst dieser 30-Sekunden-Check",
    hookDe: "Eine fehlende Angabe auf der Rechnung, und der Kunde zahlt später. Oder der Steuerberater ruft an.",
    hookRu: "Одна недостающая строка в счёте — и клиент платит позже. Или звонит бухгалтер.",
    midDe: "Bevor du sendest: Rechnung als PDF in die KI, persönliche Daten vorher abdecken. Prompt: «Prüfe diese Rechnung: Welche üblichen Pflichtangaben fehlen? Ist die Nummerierung schlüssig, sind Datum, Leistungszeitraum und Zahlungsziel klar? Gibt es Formulierungen, die Rückfragen auslösen? Liste nur die Probleme auf.» Dreißig Sekunden. Die endgültige Prüfung macht dein Steuerberater — aber du schickst keine halbe Rechnung mehr raus.",
    midRu: "Перед отправкой: счёт в PDF загрузи в ИИ, личные данные заранее закрой. Промпт: «Проверь этот счёт: каких обычных обязательных реквизитов не хватает? Логична ли нумерация, ясны ли дата, период работ и срок оплаты? Есть ли формулировки, которые вызовут вопросы? Перечисли только проблемы». Тридцать секунд. Финальную проверку делает бухгалтер — но недоделанный счёт ты больше не отправишь.",
    cta: "C",
    saveWhy: "Страх «ошибка в счёте» + быстрый чек = сохраняют перед ближайшей отправкой.",
    captionDe: "Vor dem Senden: 30 Sekunden.\n\n„Prüfe diese Rechnung: Welche üblichen Pflichtangaben fehlen? Ist die Nummerierung schlüssig, sind Datum, Leistungszeitraum und Zahlungsziel klar? Gibt es Formulierungen, die Rückfragen auslösen? Liste nur die Probleme auf.“\n\nPersönliche Daten vorher abdecken.\nDie verbindliche Prüfung macht dein Steuerberater — dieser Check verhindert nur die dummen Fehler.\n\nSchreib „KI“ in die Kommentare, ich schicke dir den Prompt.",
    captionRu: "Перед отправкой — 30 секунд.\n\n«Проверь этот счёт: каких обычных обязательных реквизитов не хватает? Логична ли нумерация, ясны ли дата, период работ и срок оплаты? Есть ли формулировки, которые вызовут вопросы? Перечисли только проблемы».\n\nЛичные данные заранее закрыть.\nОбязательную проверку делает бухгалтер — этот чек ловит только глупые ошибки.\n\nНапиши «KI» в комментарии — пришлю промпт.",
    hashtags: ["#kimitandrii", "#rechnungstellen", "#buchhaltung", "#selbstständigkeit", "#österreich"],
    shoot: "Экран: счёт → список найденных пропусков красным. Крупный план кнопки «отправить», палец останавливается.",
  },
  {
    num: 115, group: "KI bei der Arbeit", title: "Dein CRM ist ein Zettel. Das ist das Problem.",
    hookDe: "Deine Kunden leben auf Zetteln, in WhatsApp und im Kopf. Deshalb vergisst du jede Woche Geld.",
    hookRu: "Твои клиенты живут на бумажках, в WhatsApp и в голове. Поэтому каждую неделю ты забываешь деньги.",
    midDe: "Ein Google Sheet, sechs Spalten: Name, Kontakt, woher er kam, Status, nächster Schritt, Datum. Mehr nicht. Die Spalte «nächster Schritt» ist die wichtigste — ohne sie ist es eine Adressliste. Prompt: «Bau mir eine Tabelle mit diesen sechs Spalten und zehn Beispielzeilen für [dein Geschäft].» Jeden Montag zehn Minuten: alles filtern, wo das Datum in der Vergangenheit liegt. Das sind deine Anrufe für heute — die Kunden, die du sonst verlierst.",
    midRu: "Одна Google-таблица, шесть колонок: имя, контакт, откуда пришёл, статус, следующий шаг, дата. Больше ничего. Колонка «следующий шаг» — самая важная, без неё это просто список контактов. Промпт: «Сделай таблицу с этими шестью колонками и десятью примерами строк для [твой бизнес]». Каждый понедельник десять минут: фильтруешь всё, где дата уже прошла. Это твои звонки на сегодня — клиенты, которых иначе теряешь.",
    cta: "C",
    saveWhy: "Замена «дорогой CRM» бесплатной таблицей + понедельничный ритуал: сохраняют владельцы.",
    captionDe: "Du brauchst kein CRM für 90 € im Monat. Du brauchst sechs Spalten.\n\nName · Kontakt · woher · Status · nächster Schritt · Datum\n\nDie Spalte „nächster Schritt“ ist die einzige, die Geld bringt. Ohne sie ist es eine Adressliste.\n\nPrompt: „Bau mir eine Tabelle mit diesen sechs Spalten und zehn Beispielzeilen für [mein Geschäft].“\n\nJeden Montag 10 Minuten: alles filtern, wo das Datum vorbei ist. Das sind deine Anrufe für heute.\n\nSchreib „KI“ in die Kommentare — ich schicke dir die Vorlage.",
    captionRu: "Тебе не нужна CRM за 90 € в месяц. Тебе нужно шесть колонок.\n\nИмя · контакт · откуда · статус · следующий шаг · дата\n\nКолонка «следующий шаг» — единственная, которая приносит деньги. Без неё это список контактов.\n\nПромпт: «Сделай таблицу с этими шестью колонками и десятью примерами строк для [мой бизнес]».\n\nКаждый понедельник 10 минут: фильтруешь просроченные даты. Это твои звонки на сегодня.\n\nНапиши «KI» в комментарии — пришлю шаблон.",
    hashtags: ["#kimitandrii", "#crm", "#kleinunternehmen", "#googlesheets", "#neukunden"],
    shoot: "Бумажки и стикеры на столе сметаешь в сторону → экран с таблицей из 6 колонок и фильтром по дате.",
  },

  // ─────────────────────────────  Marketing  ─────────────────────────────
  {
    num: 116, group: "Marketing", title: "Drei Felder im Google-Profil, die fast keiner ausfüllt",
    hookDe: "Dein Google-Profil ist zu 40 Prozent leer. Genau die leeren Felder entscheiden, wer dich findet.",
    hookRu: "Твой профиль в Google заполнен на 40 процентов. И именно пустые поля решают, кто тебя найдёт.",
    midDe: "Erstens: «Leistungen». Jede einzelne Leistung eintragen, mit zwei Sätzen Beschreibung. Nicht «Friseur» — sondern jede Sache, die jemand suchen könnte. Zweitens: «Fragen und Antworten». Du darfst dort selbst Fragen stellen und beantworten. Schreib die fünf Fragen rein, die Kunden dich am Telefon fragen. Drittens: Feiertags-Öffnungszeiten. Falsche Zeiten am Feiertag kosten dich einen ganzen Tag Umsatz. Zwanzig Minuten, kostenlos.",
    midRu: "Первое: «Услуги». Внести каждую услугу отдельно, с описанием в два предложения. Не «парикмахер», а каждая вещь, которую могут искать. Второе: «Вопросы и ответы». Там можно самому задать вопрос и самому ответить. Впиши пять вопросов, которые клиенты задают тебе по телефону. Третье: часы работы в праздники. Неверные часы в праздник стоят тебе целого дня выручки. Двадцать минут, бесплатно.",
    cta: "B",
    saveWhy: "Конкретные поля, которые можно открыть и заполнить сразу; владельцы пересылают админам.",
    captionDe: "20 Minuten. Null Euro. Drei Felder.\n\n1. Leistungen: jede einzelne eintragen, zwei Sätze Beschreibung. Nicht „Friseur“ — alles, was jemand suchen könnte.\n2. Fragen & Antworten: du darfst selbst fragen und selbst antworten. Nimm die fünf Fragen, die dir Kunden am Telefon stellen.\n3. Feiertags-Öffnungszeiten: falsche Zeiten am Feiertag = ein ganzer Tag Umsatz weg.\n\nDas Profil ist kostenlos. Leer bleibt es trotzdem bei den meisten.",
    captionRu: "20 минут. Ноль евро. Три поля.\n\n1. Услуги: внести каждую отдельно, описание в два предложения. Не «парикмахер», а всё, что могут искать.\n2. Вопросы и ответы: можно спрашивать и отвечать самому. Возьми пять вопросов, которые задают по телефону.\n3. Часы работы в праздники: неверные часы = минус день выручки.\n\nПрофиль бесплатный. И у большинства всё равно пустой.",
    hashtags: ["#kimitandrii", "#googlebusinessprofile", "#lokalesmarketing", "#wien", "#kleinunternehmen"],
    shoot: "Запись экрана: реальный профиль, показываешь пустые поля и заполняешь одно вживую.",
  },
  {
    num: 117, group: "Marketing", title: "Der Drei-Prompt-Test: sieht die KI dein Geschäft?",
    hookDe: "Deine Kunden fragen nicht mehr nur Google. Sie fragen die KI. Und die KI hat eine Meinung über dich.",
    hookRu: "Клиенты уже спрашивают не только Google. Они спрашивают ИИ. И у ИИ есть мнение о тебе.",
    midDe: "Drei Fragen, zwei Minuten, jetzt sofort. Erstens: «Wer ist der beste [deine Branche] in [dein Bezirk]?» — bist du dabei? Zweitens: «Was sagen Kunden über [dein Firmenname]?» — stimmt das überhaupt? Drittens: «Vergleiche [dein Name] mit [Konkurrent].» Das tut weh, ist aber die wichtigste. Screenshots machen. Was die KI über dich sagt, kommt aus Bewertungen, deiner Website und Erwähnungen — genau dort änderst du es.",
    midRu: "Три вопроса, две минуты, прямо сейчас. Первый: «Кто лучший [твоя ниша] в [твой район]?» — ты там есть? Второй: «Что клиенты говорят о [название фирмы]?» — а это вообще правда? Третий: «Сравни [твоё имя] с [конкурент]». Это больно, но он самый важный. Сделай скриншоты. То, что ИИ говорит о тебе, берётся из отзывов, сайта и упоминаний — там это и меняется.",
    cta: "D",
    saveWhy: "Самодиагностика за 2 минуты с неприятным результатом — сохраняют и пересылают партнёру по бизнесу.",
    captionDe: "Zwei Minuten. Drei Fragen. Mach sie jetzt.\n\n1. „Wer ist der beste [Branche] in [Bezirk]?“ — bist du dabei?\n2. „Was sagen Kunden über [Firmenname]?“ — stimmt das?\n3. „Vergleiche [Firmenname] mit [Konkurrent].“ — das tut weh und ist die wichtigste.\n\nScreenshots machen.\n\nDie KI erfindet nichts. Sie liest Bewertungen, deine Website, Erwähnungen. Genau dort änderst du das Ergebnis.\n\nDu willst wissen, warum du nicht vorkommst? Schreib mir „CHECK“.",
    captionRu: "Две минуты. Три вопроса. Сделай прямо сейчас.\n\n1. «Кто лучший [ниша] в [район]?» — ты там есть?\n2. «Что клиенты говорят о [название]?» — это правда?\n3. «Сравни [название] с [конкурент]». — больно, но это главный вопрос.\n\nСделай скриншоты.\n\nИИ ничего не выдумывает. Он читает отзывы, сайт, упоминания. Там и меняется результат.\n\nХочешь понять, почему тебя нет в ответах? Напиши «CHECK».",
    hashtags: ["#kimitandrii", "#kisichtbarkeit", "#chatgpt", "#unternehmenwien", "#digitalisierung"],
    shoot: "Запись экрана с тремя запросами подряд. Третий (сравнение с конкурентом) — крупно, держать паузу.",
  },
  {
    num: 118, group: "Marketing", title: "Die FAQ-Seite, aus der die KI zitiert",
    hookDe: "Die KI zitiert Websites, die Fragen beantworten. Deine Website beantwortet keine einzige.",
    hookRu: "ИИ цитирует сайты, которые отвечают на вопросы. Твой сайт не отвечает ни на один.",
    midDe: "Nimm die zehn Fragen, die Kunden dir wirklich stellen — vor dem Kauf, am Telefon, in der Tür. «Was kostet das ungefähr?», «Wie lange dauert es?», «Kommen Sie auch nach [Ort]?» Jede Frage als echte Überschrift, darunter drei Sätze mit einer klaren Antwort. Keine Werbung, keine Ausflüchte. Prompt zum Sammeln: «Was fragen Kunden, bevor sie [deine Leistung] kaufen? Zehn Fragen, nach Häufigkeit sortiert.» Solche Seiten werden zitiert — Werbetexte nicht.",
    midRu: "Возьми десять вопросов, которые клиенты реально задают — перед покупкой, по телефону, на пороге. «Сколько примерно стоит?», «Сколько по времени?», «Вы приезжаете в [место]?» Каждый вопрос — настоящий заголовок, под ним три предложения с ясным ответом. Без рекламы и увиливаний. Промпт для сбора: «Что спрашивают клиенты перед покупкой [твоя услуга]? Десять вопросов по частоте». Такие страницы цитируют — рекламные тексты нет.",
    cta: "B",
    saveWhy: "Даёт готовую структуру страницы, которую можно поручить кому угодно — сохраняют как ТЗ.",
    captionDe: "Warum zitiert die KI andere und nicht dich? Weil die anderen antworten.\n\nZehn Fragen, die deine Kunden wirklich stellen:\n„Was kostet das ungefähr?“ · „Wie lange dauert es?“ · „Kommen Sie auch nach [Ort]?“\n\nJede Frage als Überschrift. Darunter drei Sätze mit einer klaren Antwort. Keine Werbung, keine Ausflüchte.\n\nZum Sammeln: „Was fragen Kunden, bevor sie [Leistung] kaufen? Zehn Fragen, nach Häufigkeit sortiert.“\n\nWer Fragen beantwortet, wird gefunden. Von Menschen und von der KI.",
    captionRu: "Почему ИИ цитирует других, а не тебя? Потому что другие отвечают.\n\nДесять вопросов, которые клиенты реально задают:\n«Сколько примерно стоит?» · «Сколько по времени?» · «Вы приезжаете в [место]?»\n\nКаждый вопрос — заголовок. Под ним три предложения с ясным ответом. Без рекламы и увиливаний.\n\nДля сбора: «Что спрашивают клиенты перед покупкой [услуга]? Десять вопросов по частоте».\n\nКто отвечает на вопросы — того находят. И люди, и ИИ.",
    hashtags: ["#kimitandrii", "#website", "#sichtbarkeit", "#contentmarketing", "#kifürunternehmen"],
    shoot: "Экран: скучная страница «Über uns» → FAQ-страница с заголовками-вопросами. Показать ответ ИИ со ссылкой.",
  },
  {
    num: 119, group: "Marketing", title: "Ein Stern: die Antwort in drei Sätzen",
    hookDe: "Eine Ein-Stern-Bewertung schadet dir nicht. Deine Antwort darauf schon.",
    hookRu: "Отзыв на одну звезду тебе не вредит. Вредит твой ответ на него.",
    midDe: "Nicht rechtfertigen, nicht streiten, nicht am selben Abend antworten. Drei Sätze, immer gleich. Erstens: danken und den Ärger benennen — «Danke für die Rückmeldung, das war nicht in Ordnung.» Zweitens: Verantwortung ohne Ausrede — «Wir haben zu lange gebraucht.» Drittens: raus aus der Öffentlichkeit — «Bitte melden Sie sich unter [Nummer], ich möchte das persönlich lösen.» Die Bewertung liest ein Mensch. Die Antwort lesen hundert.",
    midRu: "Не оправдываться, не спорить, не отвечать в тот же вечер. Три предложения, всегда одинаково. Первое: поблагодарить и назвать проблему — «Спасибо за отзыв, так быть не должно». Второе: ответственность без отговорок — «Мы затянули со сроком». Третье: вывести из публичного поля — «Позвоните, пожалуйста, по [номер], хочу решить это лично». Отзыв читает один человек. Ответ читают сто.",
    cta: "C",
    saveWhy: "Формулу применяют в момент стресса — сохраняют заранее, чтобы не ответить сгоряча.",
    captionDe: "Die Bewertung liest einer. Deine Antwort lesen hundert.\n\nDrei Sätze, immer gleich:\n1. Danken und benennen: „Danke für die Rückmeldung, das war nicht in Ordnung.“\n2. Verantwortung, ohne Ausrede: „Wir haben zu lange gebraucht.“\n3. Raus aus der Öffentlichkeit: „Bitte melden Sie sich unter [Nummer], ich löse das persönlich.“\n\nUnd: nie am selben Abend antworten.\n\nEine ruhige Antwort auf eine schlechte Bewertung verkauft besser als zehn gute Bewertungen.\nSchreib „KI“ in die Kommentare — ich schicke dir die Vorlage.",
    captionRu: "Отзыв читает один. Твой ответ читают сто.\n\nТри предложения, всегда одинаково:\n1. Поблагодарить и назвать: «Спасибо за отзыв, так быть не должно».\n2. Ответственность без отговорок: «Мы затянули со сроком».\n3. Вывести из публичного: «Позвоните по [номер], решу лично».\n\nИ: никогда не отвечать в тот же вечер.\n\nСпокойный ответ на плохой отзыв продаёт лучше, чем десять хороших отзывов.\nНапиши «KI» в комментарии — пришлю шаблон.",
    hashtags: ["#kimitandrii", "#bewertungen", "#googlebewertungen", "#kundenservice", "#reputation"],
    shoot: "Показать два ответа рядом: агрессивный оправдывающийся и спокойный из трёх фраз. Читать вслух оба.",
  },
  {
    num: 120, group: "Marketing", title: "Instagram-Bio in drei Zeilen",
    hookDe: "Jemand klickt auf dein Profil und hat drei Sekunden. In deiner Bio steht «Leidenschaft seit 2015».",
    hookRu: "Человек заходит в твой профиль и у него три секунды. А в био написано «страсть с 2015 года».",
    midDe: "Drei Zeilen, drei Aufgaben. Zeile eins: für wen du was tust, im Klartext — «Ich schärfe Küchenmesser in Wien.» Zeile zwei: ein Beweis, kein Adjektiv — Zahl, Jahre, Ort, Referenz. Zeile drei: was der Besucher jetzt tun soll, mit einem Wort — «Schreib TERMIN». Keine Emoji-Girlande, kein «Leidenschaft», kein «wir lieben, was wir tun». Prüfen lassen: «Versteht ein Fremder in drei Sekunden, was ich anbiete und was er tun soll?»",
    midRu: "Три строки, три задачи. Строка первая: для кого и что ты делаешь, прямым текстом — «Точу кухонные ножи в Вене». Строка вторая: доказательство, а не прилагательное — цифра, годы, место, референс. Строка третья: что посетителю сделать сейчас, одним словом — «Напиши TERMIN». Никаких гирлянд из эмодзи, никакой «страсти», никакого «мы любим своё дело». Проверка: «Поймёт ли незнакомый человек за три секунды, что я предлагаю и что ему делать?»",
    cta: "C",
    saveWhy: "Шаблон, который применяют сразу в своём профиле — плюс комментарии с «проверь моё био».",
    captionDe: "Drei Sekunden. Drei Zeilen. Mehr hast du nicht.\n\nZeile 1: für wen du was tust, im Klartext. „Ich schärfe Küchenmesser in Wien.“\nZeile 2: ein Beweis statt eines Adjektivs — Zahl, Jahre, Ort, Referenz.\nZeile 3: was der Besucher jetzt tun soll, in einem Wort. „Schreib TERMIN.“\n\nRaus: „Leidenschaft seit 2015“, Emoji-Girlanden, „wir lieben, was wir tun“.\n\nSchreib deine drei Zeilen in die Kommentare — ich sage dir, welche Zeile nicht funktioniert.",
    captionRu: "Три секунды. Три строки. Больше у тебя нет.\n\nСтрока 1: для кого и что ты делаешь, прямым текстом. «Точу кухонные ножи в Вене».\nСтрока 2: доказательство вместо прилагательного — цифра, годы, место, референс.\nСтрока 3: что сделать посетителю прямо сейчас, одним словом. «Напиши TERMIN».\n\nУбрать: «страсть с 2015», гирлянды эмодзи, «мы любим своё дело».\n\nНапиши свои три строки в комментарии — скажу, какая не работает.",
    hashtags: ["#kimitandrii", "#instagramtipps", "#profiloptimierung", "#socialmediatipps", "#selbstständig"],
    shoot: "Экран профиля: слабое био → переписанное на три строки. Показать реальные примеры (чужие замазать).",
  },
  {
    num: 121, group: "Marketing", title: "Die erste Stunde entscheidet",
    hookDe: "Zwei Betriebe, dasselbe Angebot, derselbe Preis. Den Auftrag bekommt der, der zuerst antwortet.",
    hookRu: "Две фирмы, одно предложение, одна цена. Заказ получает тот, кто ответил первым.",
    midDe: "Wer anfragt, fragt meistens bei drei Firmen gleichzeitig an. Bau dir drei Dinge, einmal: erstens eine automatische Antwort auf Anfragen — «Danke, ich habe Ihre Anfrage. Ich melde mich heute bis 18 Uhr.» Zweitens einen Terminlink, damit niemand auf dich warten muss. Drittens eine feste Zeit am Tag für Rückrufe. Das ist kein besseres Angebot. Das ist nur schneller — und schneller gewinnt.",
    midRu: "Тот, кто пишет запрос, обычно пишет сразу в три фирмы. Настрой три вещи один раз: первое — автоматический ответ на запрос: «Спасибо, ваш запрос получен. Отвечу сегодня до 18:00». Второе — ссылка на запись, чтобы никто не ждал тебя. Третье — фиксированное время в дне на обратные звонки. Это не лучшее предложение. Это просто быстрее — и быстрее выигрывает.",
    cta: "A",
    saveWhy: "Простое объяснение, почему уходят заявки, плюс три конкретных действия.",
    captionDe: "Nicht das beste Angebot gewinnt. Das erste.\n\nWer anfragt, fragt meistens bei drei Firmen gleichzeitig an.\n\nEinmal einrichten:\n1. Automatische Antwort: „Danke, ich habe Ihre Anfrage. Ich melde mich heute bis 18 Uhr.“\n2. Terminlink, damit niemand auf dich warten muss.\n3. Eine feste Zeit am Tag für Rückrufe.\n\nDas ist kein besseres Angebot. Das ist nur schneller.\nUnd schneller gewinnt.",
    captionRu: "Выигрывает не лучшее предложение. Выигрывает первое.\n\nКто отправляет запрос, обычно пишет сразу в три фирмы.\n\nНастроить один раз:\n1. Автоответ: «Спасибо, запрос получен. Отвечу сегодня до 18:00».\n2. Ссылка на запись, чтобы никто тебя не ждал.\n3. Фиксированное время в дне на обратные звонки.\n\nЭто не лучшее предложение. Это просто быстрее.\nА быстрее — выигрывает.",
    hashtags: ["#kimitandrii", "#neukunden", "#kundenanfragen", "#kleinunternehmen", "#servicequalität"],
    shoot: "Разыграть: два телефона на столе, на одном ответ через минуту, на другом через два дня. Кто получил заказ.",
  },
  {
    num: 122, group: "Marketing", title: "Content für die ganze Woche in 30 Minuten",
    hookDe: "«Ich habe keine Zeit für Instagram» heißt meistens: «Ich weiß jeden Tag nicht, was ich posten soll.»",
    hookRu: "«У меня нет времени на Instagram» обычно значит: «Я каждый день не знаю, что постить».",
    midDe: "Sonntag, dreißig Minuten, ein Prompt: «Mein Geschäft: [was]. Meine Kunden: [wer]. Ihre häufigsten Fragen: [drei Fragen]. Mach sieben Beiträge für diese Woche. Pro Beitrag: erster Satz, drei Stichpunkte, eine Handlungsaufforderung. Kein Blabla, kein Werbedeutsch.» Dann streichst du die drei schwächsten und drehst die vier guten hintereinander. Der Trick ist nicht die KI. Der Trick ist, dass du einmal die Woche denkst statt jeden Tag.",
    midRu: "Воскресенье, тридцать минут, один промпт: «Мой бизнес: [что]. Мои клиенты: [кто]. Их частые вопросы: [три вопроса]. Сделай семь постов на эту неделю. По каждому: первая фраза, три тезиса, призыв к действию. Без воды и рекламного языка». Дальше вычёркиваешь три самых слабых и снимаешь четыре хороших подряд. Трюк не в ИИ. Трюк в том, что ты думаешь раз в неделю, а не каждый день.",
    cta: "C",
    saveWhy: "Снимает главную боль «нечего постить»; сохраняют, чтобы применить в воскресенье.",
    captionDe: "„Keine Zeit für Instagram“ heißt: „Ich weiß nicht, was ich posten soll.“\n\nSonntag, 30 Minuten, ein Prompt:\n\n„Mein Geschäft: [was]. Meine Kunden: [wer]. Ihre häufigsten Fragen: [drei Fragen]. Mach sieben Beiträge für diese Woche. Pro Beitrag: erster Satz, drei Stichpunkte, eine Handlungsaufforderung. Kein Blabla.“\n\nDann: die drei schwächsten streichen, die vier guten hintereinander drehen.\n\nDer Trick ist nicht die KI. Der Trick ist, einmal pro Woche zu denken statt jeden Tag.\n\nSchreib „KI“ in die Kommentare — ich schicke dir den Prompt.",
    captionRu: "«Нет времени на Instagram» значит: «Не знаю, что постить».\n\nВоскресенье, 30 минут, один промпт:\n\n«Мой бизнес: [что]. Мои клиенты: [кто]. Их частые вопросы: [три вопроса]. Сделай семь постов на эту неделю. По каждому: первая фраза, три тезиса, призыв к действию. Без воды».\n\nДальше: три слабых вычеркнуть, четыре хороших снять подряд.\n\nТрюк не в ИИ. Трюк в том, чтобы думать раз в неделю, а не каждый день.\n\nНапиши «KI» в комментарии — пришлю промпт.",
    hashtags: ["#kimitandrii", "#contentplan", "#socialmediamarketing", "#instagramfürunternehmen", "#kitipps"],
    shoot: "Воскресный стол, кофе, ноутбук. Экран: промпт → семь постов. Потом четыре сняты подряд в одной футболке.",
  },
  {
    num: 123, group: "Marketing", title: "Kein Werbebudget? Fünf Dinge für null Euro",
    hookDe: "«Ich habe kein Budget für Marketing.» Gut. Dann machen wir es heute für null Euro.",
    hookRu: "«У меня нет бюджета на маркетинг». Хорошо. Тогда сделаем сегодня за ноль евро.",
    midDe: "Erstens: Google-Profil vollständig ausfüllen, inklusive Fotos von dieser Woche. Zweitens: zehn Kunden persönlich um eine Bewertung bitten — nicht per Aushang, persönlich. Drittens: WhatsApp Business mit Katalog und Öffnungszeiten. Viertens: eine Kooperation mit dem Nachbargeschäft, das dieselben Kunden hat und nichts Gleiches verkauft. Fünftens: in drei lokalen Verzeichnissen eintragen, überall exakt dieselben Daten. Ein Nachmittag. Null Euro. Mehr Wirkung als die ersten 300 Euro Werbung.",
    midRu: "Первое: полностью заполнить профиль Google, включая фото за эту неделю. Второе: попросить десять клиентов об отзыве лично — не объявлением, а лично. Третье: WhatsApp Business с каталогом и часами работы. Четвёртое: договориться с соседним бизнесом, у которого те же клиенты и другой товар. Пятое: зарегистрироваться в трёх локальных справочниках, везде абсолютно одинаковые данные. Один день. Ноль евро. Эффект больше, чем от первых 300 евро рекламы.",
    cta: "E",
    saveWhy: "Пять шагов без денег — сохраняют и реально отмечают галочками.",
    captionDe: "Kein Budget ist keine Ausrede. Fünf Dinge, null Euro, ein Nachmittag.\n\n1. Google-Profil komplett ausfüllen, mit Fotos von dieser Woche.\n2. Zehn Kunden persönlich um eine Bewertung bitten. Persönlich, nicht per Aushang.\n3. WhatsApp Business mit Katalog und Öffnungszeiten.\n4. Eine Kooperation mit dem Nachbargeschäft: gleiche Kunden, anderes Produkt.\n5. Drei lokale Verzeichnisse, überall exakt dieselben Daten.\n\nDas wirkt mehr als die ersten 300 Euro Werbung.\n\nUnd wenn deine Website der Bremsklotz ist: schreib mir „SITE“.",
    captionRu: "Нет бюджета — не отговорка. Пять вещей, ноль евро, один день.\n\n1. Полностью заполнить профиль Google, с фото за эту неделю.\n2. Попросить десять клиентов об отзыве лично. Лично, не объявлением.\n3. WhatsApp Business с каталогом и часами работы.\n4. Договорённость с соседним бизнесом: те же клиенты, другой товар.\n5. Три локальных справочника, везде одинаковые данные.\n\nЭффекта больше, чем от первых 300 евро рекламы.\n\nА если тормозит сайт — напиши «SITE».",
    hashtags: ["#kimitandrii", "#lokalesmarketing", "#wienbusiness", "#kleinunternehmen", "#marketingtipps"],
    shoot: "Прогулка по району: снимаешь витрины соседних бизнесов, пять пунктов как титры с галочками.",
  },

  // ─────────────────────────────  Verkauf  ─────────────────────────────
  {
    num: 124, group: "Verkauf", title: "Preis sagen und schweigen",
    hookDe: "Du sagst den Preis — und redest sofort weiter. Genau da verlierst du das Geld.",
    hookRu: "Ты называешь цену — и тут же продолжаешь говорить. Именно здесь ты теряешь деньги.",
    midDe: "«Das kostet 1.200 Euro, aber wir können schauen, vielleicht geht auch weniger…» Der Kunde hat noch gar nichts gesagt, und du hast schon verhandelt — gegen dich selbst. Die Regel: Preis nennen, Punkt, Mund zu. Drei Sekunden Stille. Die fühlen sich wie eine Minute an, aber die Stille gehört jetzt ihm. Er muss reagieren. Oft sagt er einfach «okay». Übe das laut zu Hause, bevor du es beim Kunden übst.",
    midRu: "«Это стоит 1200 евро, но можно посмотреть, возможно и меньше…» Клиент ещё ничего не сказал, а ты уже поторговался — сам с собой. Правило: назвал цену, точка, рот закрыт. Три секунды тишины. Они ощущаются как минута, но тишина теперь его. Ему надо реагировать. Часто он просто говорит «хорошо». Тренируй это вслух дома, а не на клиенте.",
    cta: "A",
    saveWhy: "Узнаваемая привычка, которую видно у себя сразу; пересылают продажникам и мастерам.",
    captionDe: "„Das kostet 1.200 — aber wir können schauen, vielleicht…“\n\nStopp. Der Kunde hat noch nichts gesagt, und du hast schon gegen dich selbst verhandelt.\n\nDie Regel: Preis nennen. Punkt. Mund zu. Drei Sekunden Stille.\n\nDie drei Sekunden fühlen sich an wie eine Minute. Aber jetzt gehört die Stille ihm — er muss reagieren. Sehr oft sagt er einfach: okay.\n\nÜb das laut zu Hause, nicht beim Kunden.\nSchick es jemandem, der beim Preis immer nervös wird.",
    captionRu: "«Это стоит 1200 — но можно посмотреть, возможно…»\n\nСтоп. Клиент ещё ничего не сказал, а ты уже поторговался сам с собой.\n\nПравило: назвал цену. Точка. Рот закрыт. Три секунды тишины.\n\nЭти три секунды ощущаются как минута. Но тишина теперь его — реагировать ему. Очень часто он просто говорит: хорошо.\n\nТренируй вслух дома, а не на клиенте.\nОтправь тому, кто всегда нервничает на цене.",
    hashtags: ["#kimitandrii", "#verkaufstipps", "#preisgespräch", "#selbstständig", "#vertrieb"],
    shoot: "Разыграть за двоих со сменой ракурса: плохая версия и правильная с настоящей паузой в 3 секунды на экране.",
  },
  {
    num: 125, group: "Verkauf", title: "Das Angebot ist nicht tot. Es liegt nur da.",
    hookDe: "Du hast das Angebot geschickt. Keine Antwort. Du schreibst nicht nach, weil du nicht nerven willst. Das Angebot ist jetzt tot.",
    hookRu: "Ты отправил смету. Ответа нет. Ты не пишешь, чтобы не надоедать. Смета теперь мертва.",
    midDe: "Tag drei, drei Zeilen, kein «Ich wollte nur kurz nachfragen». So geht es: «Guten Tag [Name], zwei Fragen zum Angebot von Montag: Passt der Umfang so für Sie? Und passt der Termin im [Monat]? Wenn etwas fehlt, sagen Sie es mir — ich passe es an.» Warum das funktioniert: es enthält eine konkrete Frage statt einer Erinnerung. Auf «Nachfragen» antwortet niemand. Auf eine Frage antworten fast alle.",
    midRu: "День третий, три строки, никаких «просто хотел уточнить». Вот так: «Добрый день, [имя], два вопроса по смете от понедельника: объём вам подходит? И срок в [месяц] подходит? Если чего-то не хватает — скажите, я поправлю». Почему работает: там конкретный вопрос вместо напоминания. На «напоминание» не отвечает никто. На вопрос отвечают почти все.",
    cta: "C",
    saveWhy: "Готовый текст, который применяют в тот же день по зависшим сметам.",
    captionDe: "Nicht nachfassen ist die teuerste Höflichkeit im Geschäft.\n\nTag 3, drei Zeilen:\n\n„Guten Tag [Name], zwei Fragen zum Angebot von Montag: Passt der Umfang so für Sie? Und passt der Termin im [Monat]? Wenn etwas fehlt, sagen Sie es mir — ich passe es an.“\n\nKein „Ich wollte nur kurz nachfragen“.\n\nAuf eine Erinnerung antwortet niemand. Auf eine konkrete Frage antworten fast alle.\n\nSchreib „KI“ in die Kommentare — ich schicke dir den Text zum Kopieren.",
    captionRu: "Не дожимать — самая дорогая вежливость в бизнесе.\n\nДень 3, три строки:\n\n«Добрый день, [имя], два вопроса по смете от понедельника: объём вам подходит? И срок в [месяц] подходит? Если чего-то не хватает — скажите, поправлю».\n\nНикаких «просто хотел уточнить».\n\nНа напоминание не отвечает никто. На конкретный вопрос отвечают почти все.\n\nНапиши «KI» в комментарии — пришлю текст для копирования.",
    hashtags: ["#kimitandrii", "#vertrieb", "#angebotnachfassen", "#verkaufstipps", "#kleinunternehmen"],
    shoot: "Экран телефона: отправленная смета, тишина, потом сообщение и ответ клиента через минуту.",
  },
  {
    num: 126, group: "Verkauf", title: "«Ich muss noch überlegen»",
    hookDe: "«Ich muss noch überlegen» heißt fast nie überlegen. Es heißt: eine Frage ist offen geblieben.",
    hookRu: "«Мне надо подумать» почти никогда не значит подумать. Это значит: остался незакрытый вопрос.",
    midDe: "Antworte nicht mit «Kein Problem, melden Sie sich». Frag stattdessen freundlich: «Klar. Damit ich Sie nicht unnötig störe — überlegen Sie beim Preis oder beim Zeitpunkt?» Zwei Türen, beide leicht zu öffnen. Beim Preis kannst du den Umfang anpassen. Beim Zeitpunkt machst du einen Termin in sechs Wochen aus. Und wenn es etwas Drittes ist, sagt er es dir jetzt — und du kannst es klären, solange er noch da ist.",
    midRu: "Не отвечай «без проблем, дайте знать». Спроси дружелюбно: «Конечно. Чтобы не беспокоить вас зря — вы думаете про цену или про сроки?» Две двери, обе легко открыть. По цене можно поправить объём. По срокам — договориться о звонке через шесть недель. А если дело в чём-то третьем, он скажет сейчас — и ты закроешь это, пока он ещё здесь.",
    cta: "A",
    saveWhy: "Одна фраза, применимая в ближайшем разговоре; пересылают в отделы продаж.",
    captionDe: "„Ich muss noch überlegen“ ist keine Absage. Es ist eine offene Frage.\n\nFalsch: „Kein Problem, melden Sie sich.“\n\nRichtig, freundlich gefragt:\n„Klar. Damit ich Sie nicht unnötig störe — überlegen Sie beim Preis oder beim Zeitpunkt?“\n\nPreis → Umfang anpassen.\nZeitpunkt → Termin in sechs Wochen fixieren.\nEtwas anderes → er sagt es dir jetzt, solange er noch vor dir steht.\n\nEine Frage. Kein Druck. Deutlich mehr Aufträge.",
    captionRu: "«Мне надо подумать» — это не отказ. Это незакрытый вопрос.\n\nНеправильно: «Без проблем, дайте знать».\n\nПравильно, дружелюбно:\n«Конечно. Чтобы не беспокоить зря — вы думаете про цену или про сроки?»\n\nЦена → поправить объём.\nСроки → назначить контакт через шесть недель.\nЧто-то третье → он скажет сейчас, пока стоит перед тобой.\n\nОдин вопрос. Без давления. Заметно больше заказов.",
    hashtags: ["#kimitandrii", "#einwandbehandlung", "#verkaufstipps", "#vertrieb", "#selbstständigkeit"],
    shoot: "Диалог за двоих. После вопроса — пауза и крупный план лица «клиента», который начинает объяснять.",
  },
  {
    num: 127, group: "Verkauf", title: "Vier Zeilen statt PDF-Angebot",
    hookDe: "Bis dein PDF-Angebot fertig ist, hat der Kunde schon jemand anderen genommen.",
    hookRu: "Пока твоя PDF-смета готовится, клиент уже выбрал другого.",
    midDe: "Bei kleinen Aufträgen: antworte in WhatsApp, vier Zeilen. Erstens, was du machst, in einem Satz. Zweitens, was es kostet: «Fixpreis 340 Euro» — nicht «circa». Drittens, wann: «Dienstag oder Donnerstag, Vormittag». Viertens eine Frage, die nur mit Ja oder Nein beantwortet wird: «Passt Dienstag?» Ein PDF ist eine Hausaufgabe für den Kunden. Vier Zeilen sind eine Entscheidung. Große Projekte bleiben schriftlich und ausführlich — dort gehört das PDF hin.",
    midRu: "На мелких заказах: отвечай в WhatsApp, четыре строки. Первая — что ты делаешь, одним предложением. Вторая — сколько стоит: «фиксированно 340 евро», а не «примерно». Третья — когда: «вторник или четверг, до обеда». Четвёртая — вопрос с ответом да/нет: «Вторник подходит?» PDF — это домашнее задание для клиента. Четыре строки — это решение. Крупные проекты остаются подробными в письменном виде, вот там PDF и нужен.",
    cta: "C",
    saveWhy: "Меняет скорость ответа сегодня же; ремесленники узнают свою потерю заказов.",
    captionDe: "Ein PDF ist eine Hausaufgabe. Vier Zeilen sind eine Entscheidung.\n\nBei kleinen Aufträgen, direkt in WhatsApp:\n1. Was du machst — ein Satz.\n2. Was es kostet: „Fixpreis 340 Euro“. Nicht „circa“.\n3. Wann: „Dienstag oder Donnerstag, Vormittag“.\n4. Eine Ja-Nein-Frage: „Passt Dienstag?“\n\nGroße Projekte bleiben ausführlich und schriftlich. Aber der Termin am Dienstag stirbt im PDF-Ordner.\n\nSchreib „KI“ in die Kommentare — ich schicke dir die Vorlage.",
    captionRu: "PDF — это домашнее задание. Четыре строки — это решение.\n\nНа мелких заказах, прямо в WhatsApp:\n1. Что делаешь — одно предложение.\n2. Сколько стоит: «фиксированно 340 евро». Не «примерно».\n3. Когда: «вторник или четверг, до обеда».\n4. Вопрос да/нет: «Вторник подходит?»\n\nКрупные проекты остаются подробными и письменными. Но заказ на вторник умирает в папке с PDF.\n\nНапиши «KI» в комментарии — пришлю шаблон.",
    hashtags: ["#kimitandrii", "#whatsappbusiness", "#angebot", "#handwerk", "#verkaufstipps"],
    shoot: "Сплит-экран: слева ноутбук с версткой PDF, справа четыре строки в WhatsApp и ответ «passt».",
  },
  {
    num: 128, group: "Verkauf", title: "Preise erhöhen, ohne Kunden zu verlieren",
    hookDe: "Deine Preise sind von 2022. Deine Kosten nicht.",
    hookRu: "Твои цены из 2022 года. Твои расходы — нет.",
    midDe: "Der Ablauf, der funktioniert: Vier Wochen vorher informieren, nicht am selben Tag. Ein Satz, ohne Entschuldigung: «Ab dem ersten [Monat] gelten neue Preise: [Zahl].» Kein «leider», kein Roman über Inflation — Erklärungen laden zum Verhandeln ein. Stammkunden bekommen einen Bonus: alte Preise noch für alle Termine bis Monatsende. Wer wegen zehn Prozent geht, war ohnehin bei jedem Billigeren weg. Und die Kunden, die bleiben, bemerken es meistens gar nicht.",
    midRu: "Работающий порядок: предупредить за четыре недели, а не в тот же день. Одно предложение, без извинений: «С первого [месяц] действуют новые цены: [цифра]». Никаких «к сожалению» и романов про инфляцию — объяснения приглашают торговаться. Постоянным — бонус: старые цены на все записи до конца месяца. Кто уйдёт из-за десяти процентов, всё равно ушёл бы к любому, кто дешевле. А те, кто остаются, чаще всего вообще не замечают.",
    cta: "C",
    saveWhy: "Страшное действие разложено на шаги + готовая формулировка — сохраняют «на январь».",
    captionDe: "Deine Preise sind von 2022. Deine Kosten nicht.\n\nDer Ablauf:\n1. Vier Wochen vorher informieren. Nicht am selben Tag.\n2. Ein Satz, ohne Entschuldigung: „Ab dem ersten [Monat] gelten neue Preise: [Zahl].“\n3. Kein „leider“, keine Erklärung. Erklärungen laden zum Verhandeln ein.\n4. Stammkunden: alte Preise für alle Termine bis Monatsende.\n\nWer wegen zehn Prozent geht, war beim nächsten Billigeren sowieso weg.\n\nSchreib „KI“ in die Kommentare — ich schicke dir den Text für die Ankündigung.",
    captionRu: "Твои цены из 2022. Твои расходы — нет.\n\nПорядок:\n1. Предупредить за четыре недели. Не в тот же день.\n2. Одно предложение без извинений: «С первого [месяц] новые цены: [цифра]».\n3. Никаких «к сожалению» и объяснений. Объяснения приглашают торговаться.\n4. Постоянным: старые цены на все записи до конца месяца.\n\nКто уходит из-за десяти процентов — ушёл бы к первому, кто дешевле.\n\nНапиши «KI» в комментарии — пришлю текст объявления.",
    hashtags: ["#kimitandrii", "#preiserhöhung", "#preise", "#selbstständigkeit", "#kleinunternehmen"],
    shoot: "Прайс-лист на столе, зачёркиваешь старую цену маркером. Текст объявления крупно на экране.",
  },
  {
    num: 129, group: "Verkauf", title: "Drei Sätze, nach denen du Nein sagst",
    hookDe: "Dieser Kunde bringt dir 800 Euro und kostet dich 2.000. Du erkennst ihn im ersten Gespräch.",
    hookRu: "Этот клиент принесёт 800 евро и обойдётся в 2000. Ты узнаёшь его на первом разговоре.",
    midDe: "Erster Satz: «Machen Sie mir einen guten Preis, dann bringe ich Ihnen viele Kunden.» Die Kunden kommen nie, der Rabatt bleibt. Zweiter: «Das ist doch schnell gemacht.» Er entscheidet über deinen Aufwand, bevor er weiß, was es ist. Dritter: «Der vorige Handwerker war eine Katastrophe» — bei drei Vorgängern bist du der vierte in der Geschichte. Nein sagen ist ein Satz: «Ich glaube, ich bin nicht der Richtige dafür — ich wünsche Ihnen viel Erfolg.» Der Platz gehört dann einem guten Kunden.",
    midRu: "Первая фраза: «Сделайте хорошую цену — приведу вам много клиентов». Клиенты не приходят никогда, скидка остаётся. Вторая: «Это же быстро делается». Он решает за твои трудозатраты, ещё не зная, в чём работа. Третья: «Прошлый мастер был катастрофой» — если предшественников трое, ты будешь четвёртым в этой истории. Отказ — это одно предложение: «Думаю, я вам не подхожу — удачи вам». Освободившееся место займёт хороший клиент.",
    cta: "A",
    saveWhy: "Каждый узнаёт своего худшего клиента; пересылают коллегам с «это про нашего».",
    captionDe: "Der Kunde, der 800 Euro bringt und 2.000 kostet. Drei Warnsätze:\n\n1. „Machen Sie mir einen guten Preis, dann bringe ich Ihnen viele Kunden.“ — Die Kunden kommen nie. Der Rabatt bleibt.\n2. „Das ist doch schnell gemacht.“ — Er entscheidet über deinen Aufwand, bevor er ihn kennt.\n3. „Der vorige Handwerker war eine Katastrophe.“ — Bei drei Vorgängern bist du Nummer vier in derselben Geschichte.\n\nNein sagen ist ein Satz:\n„Ich glaube, ich bin nicht der Richtige dafür — ich wünsche Ihnen viel Erfolg.“\n\nDer Platz gehört danach einem guten Kunden.",
    captionRu: "Клиент, который принесёт 800 евро и обойдётся в 2000. Три тревожные фразы:\n\n1. «Сделайте хорошую цену — приведу много клиентов». — Клиенты не приходят. Скидка остаётся.\n2. «Это же быстро делается». — Он решает за твои трудозатраты, не зная их.\n3. «Прошлый мастер был катастрофой». — Если предшественников трое, ты четвёртый в той же истории.\n\nОтказ — это одно предложение:\n«Думаю, я вам не подхожу — удачи вам».\n\nЭто место потом займёт хороший клиент.",
    hashtags: ["#kimitandrii", "#kundenauswahl", "#selbstständig", "#handwerk", "#businesstipps"],
    shoot: "Разыграть три фразы от лица клиента, каждую — с красным крестом-титром. В конце спокойный отказ.",
  },
  {
    num: 130, group: "Verkauf", title: "Dein echter Stundensatz",
    hookDe: "Du rechnest 45 Euro die Stunde. Verdienst du 45 Euro die Stunde? Nein.",
    hookRu: "Ты выставляешь 45 евро в час. Ты зарабатываешь 45 евро в час? Нет.",
    midDe: "Rechne einmal ehrlich mit. Nimm eine normale Woche: wie viele Stunden hast du wirklich einem Kunden verrechnet? Meistens weniger als die Hälfte — Angebote, Fahrten, Einkauf, Buchhaltung zahlt dir niemand. Dann die zweite Zahl: alle Kosten im Monat, geschäftlich und privat, plus das, was du verdienen willst. Diese Summe geteilt durch die wirklich verrechenbaren Stunden — das ist dein Mindestsatz. Fast immer ist er höher als der Preis, den du gerade nennst.",
    midRu: "Посчитай один раз честно. Возьми обычную неделю: сколько часов ты реально выставил клиенту? Обычно меньше половины — сметы, разъезды, закупки, бухгалтерию тебе не оплачивает никто. Потом вторая цифра: все расходы за месяц, рабочие и личные, плюс то, что хочешь заработать. Эту сумму раздели на реально оплачиваемые часы — это твоя минимальная ставка. Почти всегда она выше той цены, которую ты называешь сейчас.",
    cta: "B",
    saveWhy: "Считают прямо в комментариях; после расчёта многие меняют цены — сильная причина сохранить.",
    captionDe: "45 Euro die Stunde? Rechnen wir kurz nach.\n\n1. Eine normale Woche: wie viele Stunden hast du wirklich einem Kunden verrechnet? Meistens weniger als die Hälfte. Angebote, Fahrten, Einkauf, Buchhaltung zahlt dir niemand.\n2. Alle Kosten im Monat — geschäftlich und privat — plus das, was du verdienen willst.\n3. Summe geteilt durch die verrechenbaren Stunden.\n\nDas ist dein Mindestsatz. Nicht dein Wunschpreis.\n\nFast immer liegt er über dem, was gerade auf deinen Angeboten steht.\n\nWillst du das für dein Geschäft durchrechnen? Schreib mir „KI“.",
    captionRu: "45 евро в час? Давай посчитаем.\n\n1. Обычная неделя: сколько часов реально выставлено клиенту? Обычно меньше половины. Сметы, разъезды, закупки, бухгалтерию не оплачивает никто.\n2. Все расходы за месяц — рабочие и личные — плюс то, что хочешь заработать.\n3. Сумму делишь на оплачиваемые часы.\n\nЭто твоя минимальная ставка. Не желаемая цена.\n\nПочти всегда она выше той, что стоит сейчас в твоих сметах.\n\nХочешь посчитать под свой бизнес? Напиши «KI».",
    hashtags: ["#kimitandrii", "#stundensatz", "#kalkulation", "#selbstständigkeit", "#handwerk"],
    shoot: "Считать маркером на бумаге или доске прямо в кадре: часы, расходы, деление. Финальная цифра крупно.",
  },
];
